spring:
  datasource:
    url: jdbc:mysql://localhost:3306/class_booking_system
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true